create table if not exists public.game_results (
  id bigint generated by default as identity primary key,
  character text not null,
  player_count integer not null check (player_count between 1 and 30),
  scores jsonb not null,
  completed_at timestamptz not null,
  created_at timestamptz not null default now()
);

-- Legacy rows are anonymous. Apply migrations/20260908_game_history.sql after this
-- bootstrap for teacher-private nickname scoreboards and average rankings.
alter table public.game_results enable row level security;

create table if not exists public.teacher_character_preferences (
  teacher_id uuid primary key references auth.users(id) on delete cascade,
  ordered_chars text[] not null default array[
    '木','水','人','十','一','二','三','四','五','六',
    '七','八','九','日','月','山','火','口','大','小'
  ]::text[],
  approved_characters jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

-- Existing single lists migrate lazily to a per-teacher default folder on read.
alter table public.teacher_character_preferences
  add column if not exists folders jsonb;

alter table public.teacher_character_preferences
  add column if not exists active_folder_id text;
alter table public.teacher_character_preferences enable row level security;

drop policy if exists "Teachers can read own character preferences"
  on public.teacher_character_preferences;
create policy "Teachers can read own character preferences"
  on public.teacher_character_preferences
  for select
  using (auth.uid() = teacher_id);

drop policy if exists "Teachers can insert own character preferences"
  on public.teacher_character_preferences;
create policy "Teachers can insert own character preferences"
  on public.teacher_character_preferences
  for insert
  with check (auth.uid() = teacher_id);

drop policy if exists "Teachers can update own character preferences"
  on public.teacher_character_preferences;
create policy "Teachers can update own character preferences"
  on public.teacher_character_preferences
  for update
  using (auth.uid() = teacher_id)
  with check (auth.uid() = teacher_id);
