-- HANJA WORKSHOP / NEW EMPTY SUPABASE PROJECT ONLY
-- Schema and permissions only. No teacher or student records.
-- Generated from repository schema files; reviewed 2026-09-09.

begin;

-- SOURCE: apps/server/supabase.sql
create table if not exists public.game_results (
  id bigint generated by default as identity primary key,
  character text not null,
  player_count integer not null check (player_count between 1 and 30),
  scores jsonb not null,
  completed_at timestamptz not null,
  created_at timestamptz not null default now()
);

-- Legacy rows are anonymous. Apply migrations/20260908_game_history.sql after this
-- bootstrap for teacher-private nickname scoreboards and average rankings.
alter table public.game_results enable row level security;

create table if not exists public.teacher_character_preferences (
  teacher_id uuid primary key references auth.users(id) on delete cascade,
  ordered_chars text[] not null default array[
    '木','水','人','十','一','二','三','四','五','六',
    '七','八','九','日','月','山','火','口','大','小'
  ]::text[],
  approved_characters jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

-- Existing single lists migrate lazily to a per-teacher default folder on read.
alter table public.teacher_character_preferences
  add column if not exists folders jsonb;

alter table public.teacher_character_preferences
  add column if not exists active_folder_id text;
alter table public.teacher_character_preferences enable row level security;

drop policy if exists "Teachers can read own character preferences"
  on public.teacher_character_preferences;
create policy "Teachers can read own character preferences"
  on public.teacher_character_preferences
  for select
  using (auth.uid() = teacher_id);

drop policy if exists "Teachers can insert own character preferences"
  on public.teacher_character_preferences;
create policy "Teachers can insert own character preferences"
  on public.teacher_character_preferences
  for insert
  with check (auth.uid() = teacher_id);

drop policy if exists "Teachers can update own character preferences"
  on public.teacher_character_preferences;
create policy "Teachers can update own character preferences"
  on public.teacher_character_preferences
  for update
  using (auth.uid() = teacher_id)
  with check (auth.uid() = teacher_id);

-- SOURCE: apps/server/migrations/20260908_game_history.sql
-- Existing anonymous records remain untouched and cannot be assigned to a teacher.
alter table public.game_results add column if not exists result_key uuid;
alter table public.game_results add column if not exists teacher_id uuid references auth.users(id) on delete cascade;
alter table public.game_results add column if not exists game_mode text;
alter table public.game_results add column if not exists status text not null default 'completed';
create unique index if not exists game_results_result_key on public.game_results(result_key);
create index if not exists game_results_teacher_mode_date on public.game_results(teacher_id, game_mode, completed_at desc);
alter table public.game_results enable row level security;
revoke all on public.game_results from anon, authenticated;
grant select on public.game_results to authenticated;
grant all on public.game_results to service_role;
drop policy if exists teacher_read_own_results on public.game_results;
create policy teacher_read_own_results on public.game_results for select to authenticated using ((select auth.uid()) = teacher_id);

create or replace function public.teacher_result_leaderboard(p_teacher_id uuid, p_game_mode text)
returns table(nickname text, average numeric, games bigint, rank bigint)
language sql stable security invoker set search_path = '' as $$
  with averages as (
    select s->>'nickname' as nickname, round(avg((s->>'score')::numeric), 2) as average, count(*) as games
    from public.game_results r cross join lateral jsonb_array_elements(r.scores) s
    where r.teacher_id = p_teacher_id and r.game_mode = p_game_mode and r.status = 'completed'
      and s->>'nickname' is not null
    group by s->>'nickname'
  )
  select nickname, average, games, dense_rank() over(order by average desc) as rank
  from averages order by average desc, nickname;
$$;
revoke all on function public.teacher_result_leaderboard(uuid, text) from public, anon, authenticated;
grant execute on function public.teacher_result_leaderboard(uuid, text) to service_role;

-- SOURCE: apps/server/migrations/20260908_game_history_sequence.sql
-- Identity inserts require sequence privileges separately from table privileges.
grant usage, select on sequence public.game_results_id_seq to service_role;
notify pgrst, 'reload schema';

commit;

-- All three values should be true.
select
  to_regclass('public.game_results') is not null
    and to_regclass('public.teacher_character_preferences') is not null as tables_ready,
  to_regprocedure('public.teacher_result_leaderboard(uuid,text)') is not null as ranking_ready,
  has_sequence_privilege('service_role', 'public.game_results_id_seq', 'USAGE') as sequence_ready;
